FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/ ./src/
WORKDIR /src/src/ConsertaPraMim.Web.Admin
RUN dotnet publish ConsertaPraMim.Web.Admin.csproj -c Release -o /out/web-admin /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=build /out/web-admin ./
ENTRYPOINT ["dotnet", "ConsertaPraMim.Web.Admin.dll"]
