FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/ ./src/
WORKDIR /src/src/ConsertaPraMim.Web.CpmFull
RUN dotnet publish ConsertaPraMim.Web.CpmFull.csproj -c Release -o /out/web-cpmfull /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=build /out/web-cpmfull ./
ENTRYPOINT ["dotnet", "ConsertaPraMim.Web.CpmFull.dll"]
