FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/ ./src/
WORKDIR /src/src/ConsertaPraMim.Web.Client
RUN dotnet publish ConsertaPraMim.Web.Client.csproj -c Release -o /out/web-client /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=build /out/web-client ./
ENTRYPOINT ["dotnet", "ConsertaPraMim.Web.Client.dll"]
