FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/ ./src/
WORKDIR /src/src/ConsertaPraMim.Web.Landing
RUN dotnet publish ConsertaPraMim.Web.Landing.csproj -c Release -o /out/web-landing /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=build /out/web-landing ./
ENTRYPOINT ["dotnet", "ConsertaPraMim.Web.Landing.dll"]
